# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_useprofile_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseProfile',
            new_name='UserProfile',
        ),
    ]
