# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20171004_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_icon',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
