# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_menu_url_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price', models.PositiveIntegerField(default=19800)),
                ('outline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('qq', models.CharField(max_length=64, unique=True)),
                ('weixin', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.PositiveIntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], null=True)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.SmallIntegerField(choices=[(0, 'Baidu商桥'), (1, '51CTO'), (2, 'QQ群'), (3, '知乎'), (4, 'SOGO'), (5, '转介绍'), (6, '其他')])),
                ('status', models.SmallIntegerField(choices=[(0, '已报名'), (1, '未报名'), (2, '已退学')])),
                ('consult_content', models.TextField(max_length=1024)),
                ('graduated', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consult_courses', models.ManyToManyField(to='crm.Course')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='课程顾问')),
                ('referral_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_referrals', to='crm.Customer', verbose_name='转介绍')),
            ],
        ),
    ]
