# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_course_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户信息表'},
        ),
    ]
