# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=108, null=True)),
                ('pwd', models.CharField(blank=True, max_length=108, null=True)),
                ('user_cookies', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
