# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecustCourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=108, unique=True),
        ),
    ]
