# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.IntegerField(blank=True, null=True)),
                ('release_msg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='日志')),
            ],
            options={
                'verbose_name_plural': '发布任务日志',
            },
        ),
    ]
