# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_releaselog_release_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='machine_xml_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='releasetask',
            name='release_md5',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 6, 47, 16, 646699, tzinfo=utc), verbose_name='时间'),
        ),
    ]
