# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20170615_0647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleaseLog',
        ),
    ]
