# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 04:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_delete_releaselog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.IntegerField(blank=True, null=True)),
                ('release_time', models.DateTimeField(default=datetime.datetime(2017, 6, 16, 4, 2, 5, 875057, tzinfo=utc), verbose_name='时间')),
                ('release_msg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='日志')),
            ],
            options={
                'verbose_name_plural': '发布任务日志',
            },
        ),
    ]
