# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20170622_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 22, 6, 17, 31, 613439, tzinfo=utc), verbose_name='时间'),
        ),
    ]
