# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_auto_20170622_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='model',
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 22, 6, 18, 10, 527914, tzinfo=utc), verbose_name='时间'),
        ),
    ]
