# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20170622_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 22, 6, 18, 23, 276330, tzinfo=utc), verbose_name='时间'),
        ),
    ]
