# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 06:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_auto_20170622_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='model',
            field=models.CharField(default=500, max_length=32, verbose_name='磁盘型号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 22, 6, 19, 23, 172510, tzinfo=utc), verbose_name='时间'),
        ),
    ]
