# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 06:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20170622_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='model',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='磁盘型号'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='磁盘容量GB'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='pd_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='磁盘类型'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='server_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='repository.Server'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='slot',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='插槽位'),
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 22, 6, 21, 55, 690406, tzinfo=utc), verbose_name='时间'),
        ),
    ]
