# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-11 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dellserver',
            name='asset_serial_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='固定资产编号'),
        ),
        migrations.AddField(
            model_name='dellserver',
            name='is_hosts',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否为宿主机'),
        ),
        migrations.AddField(
            model_name='dellserver',
            name='physical_server_status',
            field=models.IntegerField(choices=[(1, '已装机'), (2, '未装机'), (3, '故障机')], default=2),
        ),
    ]
