# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-06 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dellserver',
            name='physical_server_status',
            field=models.IntegerField(choices=[(1, '已装机'), (2, '未装机'), (3, '故障机')], default=2),
        ),
    ]
