# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('vpn_name', models.CharField(blank=True, max_length=32, null=True)),
                ('vpn_pwd', models.CharField(blank=True, max_length=108, null=True)),
                ('active', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'vpn 账号表',
            },
        ),
    ]
