# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('ip', models.CharField(blank=True, max_length=32, null=True)),
                ('create_user', models.CharField(blank=True, max_length=32, null=True)),
                ('docker_info', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.CharField(blank=True, max_length=32, null=True)),
                ('remove_time', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'docker容器信息查询表',
            },
        ),
    ]
