# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-08 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan', models.CharField(blank=True, max_length=32, null=True)),
                ('network', models.CharField(blank=True, max_length=32, null=True)),
                ('netmask', models.CharField(blank=True, max_length=32, null=True)),
                ('getway', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vlan表',
            },
        ),
    ]
