# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-31 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicsinstall',
            name='status',
            field=models.IntegerField(choices=[(1, '待安装'), (2, '安装中'), (3, '已安装'), (4, '已失败')], default=1),
        ),
    ]
