# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='machine_host',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
