# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_dockerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
