# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_vpnaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpnaccount',
            old_name='vpn_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vpnaccount',
            old_name='vpn_pwd',
            new_name='password',
        ),
    ]
