# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170626_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备型号')),
                ('ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='管理IP')),
                ('idc', models.CharField(blank=True, max_length=32, null=True, verbose_name='机房')),
                ('cabinet', models.CharField(blank=True, max_length=32, null=True, verbose_name='机柜')),
                ('putaway', models.CharField(blank=True, max_length=32, null=True, verbose_name='上架日期')),
                ('service', models.CharField(blank=True, max_length=32, null=True, verbose_name='保修日期')),
            ],
            options={
                'verbose_name_plural': '网卡表',
            },
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 9, 19, 22, 187999, tzinfo=utc), verbose_name='时间'),
        ),
    ]
