# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_vlan'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('network', models.GenericIPAddressField(blank=True, null=True)),
                ('vlan', models.GenericIPAddressField(blank=True, null=True)),
                ('getway', models.GenericIPAddressField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=108, null=True)),
            ],
            options={
                'verbose_name_plural': 'IP地址池',
            },
        ),
    ]
