# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170816_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasetask',
            name='release_reason',
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='releasetask',
            name='release_status',
            field=models.IntegerField(blank=True, choices=[(1, '发布中'), (2, '发布成功'), (3, '发布失败'), (4, '待审核'), (5, '待发布')], default=1, null=True),
        ),
    ]
