# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-31 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20180331_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicsinstall',
            name='sn',
            field=models.CharField(max_length=108, unique=True),
        ),
    ]
