# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170816_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasetask',
            name='release_reason',
            field=models.CharField(blank=True, max_length=1080, null=True),
        ),
    ]
