# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170626_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='asset',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联资产'),
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 9, 24, 4, 688317, tzinfo=utc), verbose_name='时间'),
        ),
    ]
