# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_machinetype_machine_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinetype',
            name='machine_ip',
        ),
    ]
