# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20170626_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='harddisk',
            name='rpm',
            field=models.IntegerField(blank=True, null=True, verbose_name='磁盘转速'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='host_type',
            field=models.IntegerField(choices=[(1, '物理服务器'), (2, '虚拟机'), (3, '交换机')], default=2),
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 28, 8, 56, 50, 853669, tzinfo=utc), verbose_name='时间'),
        ),
    ]
