# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_ippool_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='network',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='vlan',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
