# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-31 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20180331_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_id', models.IntegerField(blank=True, null=True)),
                ('install_msg', models.CharField(blank=True, max_length=108, null=True, verbose_name='日志')),
                ('install_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '装机任务日志',
            },
        ),
    ]
