# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_remove_machinetype_machine_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='machine_ip',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
