# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20180313_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='disabled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vlan',
            name='online',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vlan',
            name='usable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
