# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20170831_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttask',
            old_name='git_url',
            new_name='port',
        ),
        migrations.AlterField(
            model_name='vpnaccount',
            name='active',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '冻结')], null=True),
        ),
    ]
