# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20170628_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='sn',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='sn'),
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 29, 6, 45, 40, 184667, tzinfo=utc), verbose_name='时间'),
        ),
    ]
