# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_releasetask_release_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.IntegerField(blank=True, null=True)),
                ('audit_msg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='日志')),
                ('audit_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '发布审核流程日志',
            },
        ),
        migrations.AlterField(
            model_name='releasetask',
            name='release_status',
            field=models.IntegerField(blank=True, choices=[(1, '发布中'), (2, '发布成功'), (3, '发布失败'), (4, 'PM审核'), (5, 'DB审核'), (6, 'SA审核')], default=1, null=True),
        ),
    ]
