# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-02 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_installlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ippool',
            old_name='gateway',
            new_name='getway',
        ),
        migrations.RenameField(
            model_name='vlan',
            old_name='gateway',
            new_name='getway',
        ),
    ]
