# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_machinetype_machine_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='machine_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
