# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-02 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20180402_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ippool',
            old_name='getway',
            new_name='gateway',
        ),
        migrations.RenameField(
            model_name='vlan',
            old_name='getway',
            new_name='gateway',
        ),
    ]
