# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20180313_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=108, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=108, null=True)),
                ('raid_level', models.IntegerField(blank=True, null=True)),
                ('switch_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('switch_interface', models.IntegerField(blank=True, null=True)),
                ('ilo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('server_model', models.CharField(blank=True, max_length=108, null=True)),
                ('os_version', models.CharField(blank=True, max_length=108, null=True)),
                ('vlan', models.CharField(blank=True, max_length=32, null=True)),
                ('netmask', models.IntegerField(blank=True, null=True)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '装机任务表',
            },
        ),
        migrations.RenameField(
            model_name='ippool',
            old_name='getway',
            new_name='gateway',
        ),
        migrations.RenameField(
            model_name='vlan',
            old_name='getway',
            new_name='gateway',
        ),
    ]
