# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 03:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20170629_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='brand',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='host_type',
            field=models.IntegerField(choices=[(1, '物理服务器'), (2, '虚拟机'), (3, '交换机'), (4, '防火墙')], default=2),
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 3, 12, 14, 439018, tzinfo=utc), verbose_name='时间'),
        ),
    ]
