# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20180313_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicsinstall',
            name='status',
            field=models.IntegerField(choices=[(1, '待安装'), (2, '安装中'), (3, '已安装'), (4, '已撤销')], default=1),
        ),
    ]
