# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20170630_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='pack_cmd',
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 9, 27, 41, 1332, tzinfo=utc), verbose_name='时间'),
        ),
    ]
