# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-02 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20180402_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='dellserver',
            name='asset_serial_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='固定资产编号'),
        ),
    ]
