# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20170710_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasetask',
            name='release_static_type',
            field=models.IntegerField(blank=True, choices=[(1, '迭代'), (2, '覆盖')], null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='jdk_version',
            field=models.IntegerField(blank=True, choices=[(1, 'jdk-8'), (2, 'jdk-7'), (3, 'jdk-6')], null=True),
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 8, 36, 59, 892914, tzinfo=utc), verbose_name='时间'),
        ),
    ]
