# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-02 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_physicsinstall_is_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicsinstall',
            name='is_hosts',
        ),
        migrations.AddField(
            model_name='dellserver',
            name='is_hosts',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否为宿主机'),
        ),
    ]
