# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20170717_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasetask',
            name='release_static_type',
        ),
        migrations.AddField(
            model_name='projecttask',
            name='static_type',
            field=models.IntegerField(blank=True, choices=[(1, '迭代'), (2, '覆盖')], null=True),
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 8, 41, 56, 544038, tzinfo=utc), verbose_name='时间'),
        ),
    ]
