# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20170717_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
