# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20170926_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstwo',
            name='business_url',
        ),
    ]
