# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-03 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20180402_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicsinstall',
            name='switch_interface',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
