# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20170720_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasetask',
            name='release_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releasetask',
            name='release_jdk_version',
            field=models.IntegerField(blank=True, choices=[(1, 'JDK-8'), (2, 'JDK-7'), (3, 'JDK-6')], null=True),
        ),
    ]
