# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_remove_businesstwo_business_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=32, null=True)),
                ('create_time', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'docker物理节点表',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='host_type',
            field=models.IntegerField(choices=[(1, '物理服务器'), (2, '虚拟机'), (3, '交换机'), (4, '防火墙'), (5, 'Docker')], default=2),
        ),
    ]
