# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20170409_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachines',
            name='cpu_num',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='virtualmachines',
            name='memory_num',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='virtualmachines',
            name='bussiness',
            field=models.CharField(default='kvm-test', max_length=32),
        ),
    ]
