# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0033_auto_20170508_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
