# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0035_auto_20170509_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='business_one',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_one',
            field=models.ManyToManyField(blank=True, null=True, to='repository.BusinessOne'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business_three',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_three',
            field=models.ManyToManyField(blank=True, null=True, to='repository.BusinessThree'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business_two',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_two',
            field=models.ManyToManyField(blank=True, null=True, to='repository.BusinessTwo'),
        ),
    ]
