# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0041_auto_20170510_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='repository.UserGroup'),
        ),
    ]
