# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0044_auto_20170516_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=108, null=True)),
                ('jdk_version', models.IntegerField(blank=True, choices=[(1, 'jdk-7'), (2, 'jdk-8')], null=True)),
                ('release_id', models.CharField(blank=True, max_length=32, null=True)),
                ('release_user', models.CharField(blank=True, max_length=32, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('business_1', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='repository.BusinessOne')),
                ('business_2', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='repository.BusinessTwo')),
            ],
        ),
    ]
