# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0048_projecttask_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='project_name',
        ),
        migrations.AddField(
            model_name='projecttask',
            name='release_last_time',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
