# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0051_auto_20170518_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='git_branch',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
