# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0053_auto_20170518_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='git_branch',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='releasetask',
            name='release_status',
            field=models.IntegerField(blank=True, choices=[(1, '发布中'), (2, '发布成功'), (3, '发布失败')], default=1, null=True),
        ),
    ]
