# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_auto_20170409_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalmachines',
            name='machine_type',
        ),
        migrations.RemoveField(
            model_name='virtualmachines',
            name='item',
        ),
        migrations.AddField(
            model_name='virtualmachines',
            name='machine_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.MachineType'),
        ),
    ]
