# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0028_auto_20170428_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='authinfo',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='business_1',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='repository.BusinessOne', verbose_name='业务线1'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='business_2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='repository.BusinessTwo', verbose_name='业务线2'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='business_3',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='repository.BusinessThree', verbose_name='业务线3'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='host_status',
            field=models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=2),
        ),
        migrations.AlterField(
            model_name='asset',
            name='host_type',
            field=models.IntegerField(choices=[(1, '物理服务器'), (2, '虚拟机'), (3, '网络设备')], default=2),
        ),
        migrations.AlterField(
            model_name='assets',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.BusinessUnit', verbose_name='属于的业务线'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='cabinet_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜号'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='cabinet_order',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜中序号'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='device_status_id',
            field=models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1),
        ),
        migrations.AlterField(
            model_name='assets',
            name='device_type_id',
            field=models.IntegerField(choices=[(1, '服务器'), (2, '交换机'), (3, '防火墙')], default=1),
        ),
        migrations.AlterField(
            model_name='assets',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.IDC', verbose_name='IDC机房'),
        ),
        migrations.AlterField(
            model_name='authinfo',
            name='rank',
            field=models.IntegerField(choices=[(1, 'root'), (2, 'admin'), (3, 'rd')], default=3),
        ),
        migrations.AlterField(
            model_name='authinfo',
            name='status',
            field=models.IntegerField(choices=[(1, '[申请中]'), (2, '[通过]'), (3, '[拒绝]')], default=1),
        ),
        migrations.AlterField(
            model_name='businessone',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='一级业务线'),
        ),
        migrations.AlterField(
            model_name='businessthree',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='三级业务线'),
        ),
        migrations.AlterField(
            model_name='businesstwo',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='二级业务线'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='repository.UserGroup', verbose_name='业务联系人'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m', to='repository.UserGroup', verbose_name='系统管理员'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='业务线'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.FloatField(verbose_name='磁盘容量GB'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='model',
            field=models.CharField(max_length=32, verbose_name='磁盘型号'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='pd_type',
            field=models.CharField(max_length=32, verbose_name='磁盘类型'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='slot',
            field=models.CharField(max_length=8, verbose_name='插槽位'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='楼层'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=32, verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='容量'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='model',
            field=models.CharField(max_length=64, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='slot',
            field=models.CharField(max_length=32, verbose_name='插槽位'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='sn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='内存SN号'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='speed',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='速度'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='设置详细配置'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='intranet_ip',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='management_ip',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='管理IP'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='port_num',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='端口个数'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='sn',
            field=models.CharField(max_length=64, unique=True, verbose_name='SN号'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='hwaddr',
            field=models.CharField(max_length=64, verbose_name='网卡mac地址'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='ipaddrs',
            field=models.CharField(max_length=256, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='name',
            field=models.CharField(max_length=128, verbose_name='网卡名称'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU个数'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU型号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_physical_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU物理个数'),
        ),
        migrations.AlterField(
            model_name='server',
            name='manage_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP'),
        ),
        migrations.AlterField(
            model_name='server',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='server',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_platform',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='系统'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(db_index=True, max_length=64, verbose_name='SN号'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='标签'),
        ),
    ]
