# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0029_auto_20170502_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_one',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_three',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务3'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_two',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户组'),
        ),
        migrations.AlterField(
            model_name='authinfo',
            name='status',
            field=models.IntegerField(choices=[(1, '[申请中]'), (2, '[已通过]'), (3, '[已拒绝]')], default=1),
        ),
    ]
