# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0030_auto_20170508_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='business_one',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business_three',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business_two',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务'),
        ),
    ]
