# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0031_auto_20170508_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='business_one',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务1'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='business_three',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务3'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='business_two',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_one',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_three',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务3'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_two',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务2'),
        ),
    ]
