# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0040_auto_20170510_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(max_length=64, verbose_name='业务线'),
        ),
    ]
