# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0045_projecttask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='name',
        ),
        migrations.AddField(
            model_name='projecttask',
            name='git_branch',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='git_url',
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='project_name',
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
    ]
