# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0046_auto_20170516_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, '新提交'), (2, '发布成功'), (3, '发布失败')], default=1, null=True),
        ),
    ]
