# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0047_projecttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='project_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.ReleaseType'),
        ),
    ]
