# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0049_auto_20170517_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_time', models.CharField(blank=True, max_length=32, null=True)),
                ('release_status', models.IntegerField(blank=True, choices=[(1, '发布中'), (2, '发布成功'), (3, '发布失败')], null=True)),
                ('release_user', models.CharField(blank=True, max_length=32, null=True)),
                ('release_git_url', models.CharField(blank=True, max_length=64, null=True)),
                ('release_git_branch', models.CharField(blank=True, max_length=32, null=True)),
                ('release_jdk_version', models.IntegerField(blank=True, choices=[(1, 'jdk-7'), (2, 'jdk-8')], null=True)),
                ('release_env', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.BusinessOne')),
                ('release_name', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.BusinessTwo')),
                ('release_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.ReleaseType')),
            ],
            options={
                'verbose_name_plural': '发布列表',
            },
        ),
        migrations.AlterModelOptions(
            name='projecttask',
            options={'verbose_name_plural': '项目表'},
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='release_last_time',
            field=models.CharField(blank=True, default='-', max_length=32, null=True),
        ),
    ]
