# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0055_auto_20170519_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasetask',
            options={'verbose_name_plural': '发布任务记录表'},
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='时间'),
        ),
    ]
