# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0063_auto_20170519_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 2, 45, 52, 847942, tzinfo=utc), verbose_name='时间'),
        ),
    ]
