# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0065_auto_20170531_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='business_1',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='business_2',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='releasetask',
            name='release_env',
        ),
        migrations.RemoveField(
            model_name='releasetask',
            name='release_name',
        ),
        migrations.RemoveField(
            model_name='releasetask',
            name='release_type',
        ),
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 7, 42, 50, 989184, tzinfo=utc), verbose_name='时间'),
        ),
        migrations.DeleteModel(
            name='ProjectTask',
        ),
        migrations.DeleteModel(
            name='ReleaseTask',
        ),
    ]
