# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0067_auto_20170531_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaselog',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 8, 30, 46, 976218, tzinfo=utc), verbose_name='时间'),
        ),
    ]
