# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0073_auto_20170531_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jdk_version', models.IntegerField(blank=True, choices=[(1, 'jdk-7'), (2, 'jdk-8')], null=True)),
                ('release_last_id', models.CharField(blank=True, default='-', max_length=32, null=True)),
                ('release_last_time', models.CharField(blank=True, default='-', max_length=32, null=True)),
                ('release_user', models.CharField(blank=True, max_length=32, null=True)),
                ('git_url', models.CharField(blank=True, max_length=108, null=True)),
                ('git_branch', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, '新提交'), (2, '发布成功'), (3, '发布失败')], default=1, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('business_1', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='repository.BusinessOne')),
                ('business_2', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='repository.BusinessTwo')),
                ('project_type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.ReleaseType')),
            ],
            options={
                'verbose_name_plural': '项目表',
            },
        ),
    ]
