# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0075_auto_20170531_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='git_branch',
            field=models.CharField(blank=True, default=1, max_length=108, null=True),
        ),
    ]
