# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0077_auto_20170531_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='git_branch',
        ),
        migrations.AddField(
            model_name='projecttask',
            name='git_branch_i',
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
    ]
