# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0078_auto_20170531_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='business_1',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='business_2',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='project_type',
        ),
        migrations.DeleteModel(
            name='ProjectTask',
        ),
    ]
