# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-04 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NginxHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=32, null=True)),
                ('path', models.CharField(blank=True, max_length=108, null=True)),
                ('reload_cmd', models.CharField(blank=True, max_length=108, null=True)),
            ],
            options={
                'verbose_name_plural': 'Nginx主机节点',
            },
        ),
        migrations.CreateModel(
            name='NginxLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=32, null=True)),
                ('record', models.CharField(blank=True, max_length=108, null=True)),
                ('ctime', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '修改日志表',
            },
        ),
    ]
