# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=32)),
                ('business', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=10)),
                ('idc_name', models.CharField(max_length=32)),
                ('idc_cabinet', models.CharField(max_length=32)),
                ('person', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
